<template>
  <div class="icon-picker">
    <!-- Trigger button -->
    <button class="icon-trigger" :style="{ borderColor: color + '55' }" @click.stop="open = !open">
      <OhVueIcon :name="modelValue || 'gi-scroll-unfurled'" scale="1.2" :style="{ color }" />
      <span class="icon-trigger-name">{{ modelValue || 'choose icon' }}</span>
      <OhVueIcon name="md-arrowdropdown" scale="0.9" style="color:var(--forge-muted);margin-left:auto" />
    </button>

    <!-- Dropdown -->
    <div v-if="open" class="icon-dropdown" @click.stop>
      <div class="icon-search-wrap">
        <OhVueIcon name="fa-search" scale="0.8" style="color:var(--forge-muted)" />
        <input ref="searchEl" v-model="query" class="icon-search" placeholder="Search icons…" />
        <button v-if="query" class="icon-clear" @click="query = ''">
          <OhVueIcon name="md-close" scale="0.8" />
        </button>
      </div>
      <div class="icon-grid">
        <button
          v-for="name in visible"
          :key="name"
          class="icon-cell"
          :class="{ selected: modelValue === name }"
          :title="name"
          :style="modelValue === name ? { background: color + '22', borderColor: color + '88' } : {}"
          @click="select(name)"
        >
          <OhVueIcon :name="name" scale="1.1" :style="{ color: modelValue === name ? color : '' }" />
        </button>
        <p v-if="visible.length === 0" class="icon-empty">No icons match "{{ query }}"</p>
      </div>
    </div>

    <!-- Backdrop -->
    <div v-if="open" class="icon-backdrop" @click="open = false" />
  </div>
</template>

<script setup lang="ts">
// Import the full GI name list generated by the plugin
// Falls back to a small curated list if the plugin export isn't available
const GI_ICONS = ref<string[]>([])

onMounted(async () => {
  try {
    const mod = await import('~/plugins/oh-vue-icons.client')
    if (mod.GI_ICON_NAMES?.length) {
      GI_ICONS.value = mod.GI_ICON_NAMES
    }
  } catch {
    // Fallback to known-good set
    GI_ICONS.value = [
      'gi-scroll-unfurled','gi-person','gi-broadsword','gi-treasure-map',
      'gi-open-treasure-chest','gi-american-shield','gi-magic-palm','gi-notebook',
      'gi-book-aura','gi-magic-hat','gi-house-keys','gi-sands-of-time',
      'gi-all-seeing-eye','gi-castle','gi-coins','gi-health-potion',
      'gi-candle-skull','gi-burning-skull','gi-death-note','gi-anvil-impact',
      'gi-holy-grail','gi-dragon','gi-wizard-staff','gi-lightning-sword',
      'gi-crystal-ball','gi-potion-ball','gi-dagger','gi-shield',
      'gi-tower','gi-dungeon-gate','gi-campfire','gi-wolf-head',
      'gi-skull','gi-crown','gi-diamond','gi-fire','gi-water-drop',
      'gi-lightning','gi-moon','gi-star','gi-sun','gi-tree',
      'gi-map','gi-key','gi-lock','gi-door','gi-chest',
      'gi-pouch','gi-gem','gi-ring','gi-necklace','gi-axe',
      'gi-bow-arrow','gi-crossbow','gi-spear','gi-hammer','gi-staff',
      'gi-wand','gi-orb','gi-tome','gi-scroll','gi-feather',
    ]
  }
})

const props = defineProps<{
  modelValue: string
  color?: string
}>()
const emit = defineEmits<{ 'update:modelValue': [string] }>()

const open = ref(false)
const query = ref('')
const searchEl = ref<HTMLInputElement | null>(null)

const visible = computed(() => {
  const q = query.value.toLowerCase().trim()
  const list = GI_ICONS.value.length ? GI_ICONS.value : []
  if (!q) return list.slice(0, 120)  // show first 120 when no search
  return list.filter(n => n.includes(q)).slice(0, 120)
})

watch(open, v => {
  if (v) nextTick(() => searchEl.value?.focus())
})

function select(name: string) {
  emit('update:modelValue', name)
  open.value = false
  query.value = ''
}
</script>

<style scoped>
.icon-picker { position: relative; }

.icon-trigger {
  display: flex; align-items: center; gap: 8px;
  padding: 7px 12px; border-radius: var(--r-md);
  background: var(--forge-raised); border: 1px solid;
  color: var(--forge-text); cursor: pointer;
  font-size: 13px; font-family: 'DM Sans', sans-serif;
  width: 100%; transition: all 0.15s;
}
.icon-trigger:hover { background: var(--forge-hover); }
.icon-trigger-name { font-size: 12px; color: var(--forge-muted); }

.icon-dropdown {
  position: absolute; top: calc(100% + 6px); left: 0;
  width: 320px; max-height: 360px;
  background: var(--forge-raised); border: 1px solid var(--forge-border-l);
  border-radius: var(--r-lg); box-shadow: var(--shadow-float);
  z-index: 200; display: flex; flex-direction: column; overflow: hidden;
}
.icon-backdrop {
  position: fixed; inset: 0; z-index: 199;
}

.icon-search-wrap {
  display: flex; align-items: center; gap: 8px;
  padding: 10px 12px; border-bottom: 1px solid var(--forge-border);
  flex-shrink: 0;
}
.icon-search {
  flex: 1; background: none; border: none; outline: none;
  font-size: 13px; color: var(--forge-text);
  font-family: 'DM Sans', sans-serif;
}
.icon-search::placeholder { color: var(--forge-muted); }
.icon-clear { background: none; border: none; color: var(--forge-muted); cursor: pointer; padding: 0; }

.icon-grid {
  flex: 1; overflow-y: auto;
  display: grid; grid-template-columns: repeat(8, 1fr);
  gap: 2px; padding: 8px;
}
.icon-cell {
  aspect-ratio: 1; border-radius: 6px;
  background: transparent; border: 1px solid transparent;
  display: flex; align-items: center; justify-content: center;
  cursor: pointer; transition: all 0.1s; color: var(--forge-secondary);
}
.icon-cell:hover { background: var(--forge-border); color: var(--forge-text); }
.icon-cell.selected { color: var(--forge-accent); }
.icon-empty { grid-column: 1/-1; text-align: center; color: var(--forge-muted); font-size: 12px; padding: 16px; }
</style>
